# Generated by Django 4.1.3 on 2022-11-23 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EntregaA', '0002_nosotros'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comprar_voletos',
            new_name='comprar_boletos',
        ),
    ]
